### ISSUE TITLE
Warn about program non-backward compatibility

### ISSUE THREAD

**Issue by astrelsky** [garyttierney/ghidra-batteries-included#24]
Due to the changes in the PointerDB schema in #2189 if a user upgrades a loaded program it will no longer be compatible with any version of ghidra which does not contain #2189. It is a good idea to provide a warning about this.

Technically if #2189 is never accepted it may become non forward compatible too. If that occurs I could probably come up with a solution for recovery though.

**Comment by garyttierney** [comment]
Thanks for the warning! I'm rebasing and publishing a new build today, so I'll add a note to the README.
