### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by ddkwork** [garyttierney/ghidra-batteries-included#74]
do not work on arm64 manjaro Linux from termux

**Comment by garyttierney** [comment]
Hey, I don't have a build machine for building ARM64 binaries, but I suppose this might be do-able with cross compilation. Alternatively, if you know of anywhere offering hosted ARM64 CI runners I'd be happy to set it up.

**Comment by DiskGetor** [comment]
> 嘿，我没有建立机构建ARM64（二进制文件，但我想这可能是可行的交叉汇编。 或者，如果你知道任何地方提供托管ARM64（CI选手我会很高兴将它设置。

install manjaro from termux.
![Screenshot_20210427_065522_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/116160991-8d3ac680-a725-11eb-8777-f341c0bf5cf4.jpg)
